# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 15, 58, 20, 197724, tzinfo=utc), verbose_name='date')),
                ('is_active', models.BooleanField(default=True)),
                ('emotion', models.CharField(choices=[('hope', 'Hope'), ('interest', 'Interest'), ('surprise', 'Surprise'), ('sadness', 'Sadness'), ('fear', 'Fear'), ('shame', 'Shame'), ('guilt', 'Guilt'), ('envy', 'Envy'), ('disgust', 'Disgust'), ('contempt', 'Contempt'), ('anger', 'Anger'), ('pride', 'Pride'), ('elation', 'Elation'), ('joy', 'Joy'), ('satisfaction', 'Satisfaction'), ('relief', 'Relief')], max_length=18)),
                ('intensity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 15, 58, 20, 197724, tzinfo=utc), verbose_name='date')),
                ('is_active', models.BooleanField(default=True)),
                ('tag', models.CharField(blank=True, max_length=24, null=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TempUser'),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TempUser'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Question'),
        ),
    ]
