# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180307_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allow_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='user_type',
            field=models.CharField(choices=[('s', 'Student'), ('t', 'Teacher')], default='t', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 10, 26, 56, 41306, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 10, 26, 56, 41306, tzinfo=utc), verbose_name='date'),
        ),
    ]
