# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 16:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20180309_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 16, 0, 14, 45435, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 16, 0, 14, 45435, tzinfo=utc), verbose_name='date'),
        ),
    ]
