# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180319_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 9, 30, 17, 543707, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 23, 9, 30, 17, 543707, tzinfo=utc), verbose_name='date'),
        ),
    ]
