# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180323_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 15, 49, 41, 44734, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 15, 49, 41, 44734, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
