# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20180405_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 9, 33, 0, 502536, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='allow_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 9, 33, 0, 502536, tzinfo=utc), verbose_name='date'),
        ),
    ]
