# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20180406_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='note',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=18),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 10, 2, 11, 327064, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='emotion',
            field=models.CharField(choices=[('none', 'None'), ('other', 'Other'), ('hope', 'Hope'), ('interest', 'Interest'), ('surprise', 'Surprise'), ('sadness', 'Sadness'), ('fear', 'Fear'), ('shame', 'Shame'), ('guilt', 'Guilt'), ('envy', 'Envy'), ('disgust', 'Disgust'), ('contempt', 'Contempt'), ('anger', 'Anger'), ('pride', 'Pride'), ('elation', 'Elation'), ('joy', 'Joy'), ('satisfaction', 'Satisfaction'), ('relief', 'Relief')], max_length=18),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 10, 2, 11, 327064, tzinfo=utc), verbose_name='date'),
        ),
    ]
