# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20180406_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=42)),
                ('secret', models.CharField(max_length=42)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 14, 6, 31, 428793, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 14, 6, 31, 428793, tzinfo=utc), verbose_name='date'),
        ),
    ]
