# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 09:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180504_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='email',
            field=models.CharField(default='test@email.com', max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempuser',
            name='family_name',
            field=models.CharField(default='family_name', max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 9, 36, 58, 316701, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 9, 9, 36, 58, 316701, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
