# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20180509_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='submission',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='single', max_length=12),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 11, 11, 55, 1, 467995, tzinfo=utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 11, 11, 55, 1, 467995, tzinfo=utc), verbose_name='date'),
        ),
    ]
